import { readJSON, writeJSON } from "./localStorage";
import * as dockerClient from "./docker";
import type { ContainerInspect } from "../electrobun/rpcSchema";

const STORAGE_KEY = "context-assistant.bash-aliases.v1";
const DEVCONTAINER_HOME_VOLUME = "home";

export const DEFAULT_ZSH_ALIASES_RAW = ["c=clear", "x=exit", "gl=git log --oneline --decorate --graph", "gs=git status", "o=open"].join("\n");

export type ZshAlias = {
  name: string;
  value: string;
};

export function getStoredZshAliasesRaw(): string {
  const stored = readJSON<unknown>(STORAGE_KEY);
  if (typeof stored === "string") return stored;
  return DEFAULT_ZSH_ALIASES_RAW;
}

export function setStoredZshAliasesRaw(raw: string) {
  writeJSON(STORAGE_KEY, raw);
}

export function parseZshAliasesRaw(raw: string): ZshAlias[] {
  const lines = raw.split("\n");
  const aliases: ZshAlias[] = [];
  const validName = /^[A-Za-z_][A-Za-z0-9_]*$/;

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    if (trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq <= 0) continue;
    const name = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim();
    if (!name || !value) continue;
    if (!validName.test(name)) continue;
    aliases.push({ name, value });
  }

  return aliases;
}

function escapeZshSingleQuoted(value: string): string {
  // Turn:  foo'bar  =>  'foo'\''bar'
  return value.replace(/'/g, `'\\''`);
}

export function renderZshAliasesFile(aliases: ZshAlias[]): string {
  const header = [
    "# Generated by Context Assistant",
    "# This file is rewritten when the container starts.",
    "",
  ].join("\n");

  if (aliases.length === 0) return `${header}# (no aliases)\n`;

  const body = aliases
    .map((a) => `alias ${a.name}='${escapeZshSingleQuoted(a.value)}'`)
    .join("\n");

  return `${header}${body}\n`;
}

const SHELL_BEGIN = "# >>> context-assistant aliases >>>";
const SHELL_END = "# <<< context-assistant aliases <<<";

function shellBlock(): string {
  return [
    SHELL_BEGIN,
    'if [ -d "$HOME/.bin" ]; then',
    '  export PATH="$HOME/.bin:$PATH"',
    "fi",
    'if [ -f "$HOME/.context-assistant/bash-aliases.sh" ]; then',
    '  . "$HOME/.context-assistant/bash-aliases.sh"',
    "fi",
    SHELL_END,
    "",
  ].join("\n");
}

export function upsertZshrcAliasesBlock(existing: string): string {
  const block = shellBlock().trimEnd();
  const beginIdx = existing.indexOf(SHELL_BEGIN);
  const endIdx = existing.indexOf(SHELL_END);

  // Replace existing block if present
  if (beginIdx >= 0 && endIdx >= 0 && endIdx > beginIdx) {
    const before = existing.slice(0, beginIdx).replace(/\s*$/, "");
    const after = existing.slice(endIdx + SHELL_END.length).replace(/^\s*/, "");
    const joined = [before, "", block, "", after].filter((p) => p.length > 0).join("\n");
    return `${joined.replace(/\s*$/, "")}\n`;
  }

  // Append new block
  const trimmed = existing.replace(/\s*$/, "");
  if (!trimmed) return `${block}\n`;
  return `${trimmed}\n\n${block}\n`;
}

function getHomeDirFromInspect(inspect: ContainerInspect): string | null {
  const m = inspect.mounts.find((mount) => mount.name === DEVCONTAINER_HOME_VOLUME);
  return m?.destination ?? null;
}

async function detectPreferredExecUser(containerId: string, inspect: ContainerInspect): Promise<string> {
  const labels = inspect.config.labels ?? {};
  const explicit = (labels["context-assistant.exec-user"] ?? "").trim();
  if (explicit) return explicit === "0" ? "root" : explicit;

  // Honor the container's configured user when present. This matches the terminal backend.
  const configured = (inspect.config.user ?? "").trim();
  if (configured) return configured === "0" ? "root" : configured;

  const rootUserLabel = labels["context-assistant.root-user"];
  if (!rootUserLabel || rootUserLabel === "true") return "root";

  // rootUser=false with no configured user: best-effort detect a regular user.
  try {
    const res = await dockerClient.containerExec(containerId, [
      "sh",
      "-lc",
      "awk -F: '{if($3>=1000 && $3<65534){print $1; exit}}' /etc/passwd",
    ]);
    if (res.exitCode === 0) {
      const u = res.stdout.trim();
      if (u) return u;
    }
  } catch {
    // ignore
  }

  return "root";
}

async function detectHomeDir(containerId: string, user: string): Promise<string | null> {
  const u = (user ?? "").trim();
  if (!u || u === "root" || u === "0") return "/root";
  const isUid = /^\d+$/.test(u);

  // Prefer /etc/passwd over heuristics so images like `postgres` resolve correctly.
  try {
    const res = await dockerClient.containerExec(containerId, ["sh", "-lc", "cat /etc/passwd"]);
    if (res.exitCode === 0 && res.stdout.trim()) {
      for (const line of res.stdout.split("\n")) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith("#")) continue;
        // name:pw:uid:gid:gecos:home:shell
        const parts = trimmed.split(":");
        const name = (parts[0] ?? "").trim();
        const uid = (parts[2] ?? "").trim();
        if (isUid) {
          if (uid !== u) continue;
        } else {
          if (name !== u) continue;
        }
        const home = (parts[5] ?? "").trim();
        if (home && home.startsWith("/")) return home;
        break;
      }
    }
  } catch {
    // ignore and fall back
  }

  if (isUid) return "/root";
  return `/home/${u}`;
}

function renderOpenBridgeScript(): string {
  return [
    "#!/bin/sh",
    "set -eu",
    "",
    'if [ "$#" -lt 1 ]; then',
    '  echo "usage: open <path>" >&2',
    "  exit 2",
    "fi",
    "",
    'target="$1"',
    "",
    'if [ -d "$target" ]; then',
    '  kind="directory"',
    '  abs="$(cd "$target" 2>/dev/null && pwd -P)" || {',
    '    echo "open: cannot resolve directory: $target" >&2',
    "    exit 1",
    "  }",
    'elif [ -f "$target" ]; then',
    '  kind="file"',
    '  abs="$(cd "$(dirname "$target")" 2>/dev/null && echo "$(pwd -P)/$(basename "$target")")"',
    '  if [ -z "$abs" ]; then',
    '    echo "open: cannot resolve file parent: $target" >&2',
    "    exit 1",
    "  fi",
    "else",
    '  echo "open: path does not exist: $target" >&2',
    "  exit 1",
    "fi",
    "",
    'payload="$(printf \'%s\\t%s\' "$kind" "$abs" | base64 | tr -d \'\\n\\r\')"',
    'printf \'\\033]1337;CA_OPEN_B64=%s\\007\' "$payload"',
    "",
  ].join("\n");
}

async function installOpenBridgeCommand(containerId: string, homeDir: string) {
  const binDir = `${homeDir}/.bin`;
  const openScriptPath = `${binDir}/open`;
  await dockerClient.createDirectory(containerId, binDir);
  await dockerClient.writeFile(containerId, openScriptPath, renderOpenBridgeScript());
  await dockerClient.containerExec(containerId, ["sh", "-c", `chmod +x "${openScriptPath}"`]);
}

/**
 * Apply the currently stored aliases to a running container.
 *
 * Writes:
 * - `$HOME/.context-assistant/bash-aliases.sh`
 * - ensures `$HOME/.bashrc` sources that file (idempotent, uses markers)
 */
export async function applyBashAliasesToContainer(containerId: string): Promise<void> {
  const inspect = await dockerClient.inspectContainer(containerId);
  const homeDir =
    getHomeDirFromInspect(inspect) ??
    (await detectHomeDir(containerId, await detectPreferredExecUser(containerId, inspect)));
  if (!homeDir) return;

  const raw = getStoredZshAliasesRaw();
  const aliases = parseZshAliasesRaw(raw);
  const aliasFileContent = renderZshAliasesFile(aliases);

  const configDir = `${homeDir}/.context-assistant`;
  const aliasFilePath = `${configDir}/bash-aliases.sh`;
  const bashrcPath = `${homeDir}/.bashrc`;

  await installOpenBridgeCommand(containerId, homeDir);
  await dockerClient.createDirectory(containerId, configDir);
  await dockerClient.writeFile(containerId, aliasFilePath, aliasFileContent);

  // Also patch bash so aliases work in images whose login shell is bash.
  let currentBashrc = "";
  let hadBashrc = true;
  try {
    currentBashrc = await dockerClient.readFile(containerId, bashrcPath);
  } catch {
    hadBashrc = false;
  }
  const nextBashrc = upsertZshrcAliasesBlock(currentBashrc);
  if (!hadBashrc || nextBashrc !== currentBashrc) {
    await dockerClient.writeFile(containerId, bashrcPath, nextBashrc);
  }
}

